# Generated by Django 4.2 on 2025-08-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
