# Generated by Django 4.2 on 2025-08-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='level',
        ),
    ]
