# Generated by Django 4.2 on 2025-08-08 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_remove_role_is_global'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
        ('school', '0002_alter_school_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('elementary', 'دبستان'), ('middle_school', 'راهنمایی'), ('high_school', 'دبیرستان')], default='elementry', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_memberships', to='role.role'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='school.school'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='location.city'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user'], name='school_memb_user_id_af0757_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['school'], name='school_memb_school__2ca6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name'], name='school_scho_name_0a7aed_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['city'], name='school_scho_city_id_9bbc18_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'school'), name='unique_user_school_membership'),
        ),
    ]
