# Generated by Django 4.2 on 2025-08-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_school_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, db_collation='utf8_persian_ci', editable=False, unique=True),
        ),
    ]
