# Generated by Django 4.2 on 2025-08-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_classroom_weeklyschedule_grade_classroom_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], default=0),
        ),
    ]
