# Generated by Django 4.2 on 2025-08-15 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_weeklyschedule_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('zip_file', models.FileField(upload_to='school_pano_zips/')),
                ('extracted_path', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='school.school')),
            ],
        ),
    ]
