# Generated by Django 4.2 on 2025-08-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_virtualtour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='description',
        ),
    ]
