# Generated by Django 5.2.5 on 2025-08-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionfee',
            name='installments_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
