# Generated by Django 5.2.5 on 2025-08-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_tuitionfee_installments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
