# Generated by Django 5.2.5 on 2025-09-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_salary_overtime_alter_salary_total_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
