# Generated by Django 4.2 on 2025-07-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model')),
                ('object_id', models.IntegerField(verbose_name='object_id')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='deleted at')),
                ('data', models.JSONField(verbose_name='data')),
            ],
        ),
    ]
