# Generated by Django 4.2 on 2025-08-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('global', 'Global'), ('school', 'School'), ('shop', 'Shop')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('level', models.PositiveIntegerField(default=0)),
                ('is_global', models.BooleanField(default=True)),
                ('permissions', models.ManyToManyField(blank=True, to='role.permission')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.scope')),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.scope'),
        ),
    ]
