# Generated by Django 4.2 on 2025-08-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_global',
        ),
    ]
