# Generated by Django 4.2 on 2025-08-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_permission_remove_role_created_at_role_is_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='app',
            field=models.CharField(choices=[('global', 'Global'), ('school', 'School'), ('shop', 'Shop')], default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_global',
            field=models.BooleanField(default=True),
        ),
    ]
