# Generated by Django 4.2 on 2025-08-10 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='article.newscategory')),
            ],
            options={
                'verbose_name_plural': 'News categories',
                'ordering': ['parent__id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('body', models.TextField()),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('pinned', models.BooleanField(default=False, help_text='Pin to top of list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_news', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='news_items', to='article.newscategory')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-pinned', '-published_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='newscategory',
            index=models.Index(fields=['slug'], name='article_new_slug_709115_idx'),
        ),
        migrations.AddIndex(
            model_name='newscategory',
            index=models.Index(fields=['is_active'], name='article_new_is_acti_839a7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newscategory',
            unique_together={('parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug'], name='article_new_slug_b998c5_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['published', 'published_at'], name='article_new_publish_0549aa_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['pinned'], name='article_new_pinned_52b237_idx'),
        ),
    ]
