# Generated by Django 4.2 on 2025-08-10 08:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='NewsArticle',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='article_cat_slug_1dff20_idx',
            old_name='article_new_slug_709115_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='article_cat_is_acti_5ca961_idx',
            old_name='article_new_is_acti_839a7f_idx',
        ),
        migrations.RenameIndex(
            model_name='newsarticle',
            new_name='article_new_slug_7d61c2_idx',
            old_name='article_new_slug_b998c5_idx',
        ),
        migrations.RenameIndex(
            model_name='newsarticle',
            new_name='article_new_publish_bb7acf_idx',
            old_name='article_new_publish_0549aa_idx',
        ),
        migrations.RenameIndex(
            model_name='newsarticle',
            new_name='article_new_pinned_c5c36b_idx',
            old_name='article_new_pinned_52b237_idx',
        ),
    ]
