# Generated by Django 4.2 on 2025-08-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
